sudo: required
language: node_js
cache: yarn
addons:
  chrome: stable
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - yarn build
  - cp .git dist/ -r # required by semantic release
  - cp README.md dist/
  - cd dist
  - yarn install
  - yarn semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
